version: '3.9'

services:
  app:
    container_name: ${COMPOSE_PROJECT_NAME}_app_con
    build: 
      context: ./ngxfpm
    working_dir: /usr/share/nginx/html
    hostname: webserver
    ports: #### multi (f)
      - "80:80"
      - "443:443"
    restart: always  
    volumes:
      - ./data/logs/nginx:/var/log/nginx # access.log errors.log
      - ./data/logs/php-fpm/php-fpm.log:/var/log/php-fpm.log
      - ./ngxfpm/default.conf:/etc/nginx/conf.d/default.conf
      #### (c) change it, mount dir sourcecode -> - ../.:/usr/share/nginx/html
      - ./src_test:/usr/share/nginx/html
    networks:
        cnet:
          ipv4_address: ${NGINX_IP}
    depends_on:
      - mysql_img
  mysql_img:
    container_name: ${COMPOSE_PROJECT_NAME}_mysql57_con
    build:
      context: ./mysql
    volumes:
      - ./data/logs/mysql57:${MYSQL_LOG_DIR}
      - ./data/db:${MYSQL_DATA_DIR}
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    hostname: mysql57
    restart: always 
    networks:
      cnet:
        ipv4_address: ${MYSQL_IP}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports: #### multi (g)
      - '33066:3306'
    expose:
      - '3306'

networks:
  cnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}
